### ISSUE TITLE
firebase_options 파일 가리셔야 해요!!

### ISSUE THREAD

**Issue by Yoochanhong** [ckstmznf/PeopleOfMeal#1]
api key털리면 파베 요금폭탄 나올수도 있어요,,

**Comment by kichan05** [comment]
걱정해주시고 충고해주셔서 감사합니다. 😀
이 프로젝트는 요금제가 Spark 요금제여서 괜찮을거 같은데 맞나요? 🤔

**Comment by Yoochanhong** [comment]
spark 요금제면 할당량 초과 시 자동으로 멈춘다고 알고있기는 합니다만,,
그래도 불안하니까 ignore 해주는게 좋을것 같아요...!
